name = "maestro-school-attendance-api"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "maestro-school-attendance-db"
database_id = "2a48871e-b5ee-48c9-9678-546cf19817c6"

[vars]
FRONTEND_ORIGIN = "http://localhost:5173"
