export interface Env { DB:D1Database; FRONTEND_ORIGIN:string }
type Auth={userId:number;schoolId:number;role:string;fullName:string;username:string};
const json=(data:unknown,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8",...headers}});
const cors=(env:Env)=>({"access-control-allow-origin":env.FRONTEND_ORIGIN||"*","access-control-allow-headers":"Authorization, Content-Type","access-control-allow-methods":"GET,POST,PUT,PATCH,DELETE,OPTIONS"});
const fail=(m:string,s=400,h:HeadersInit={})=>json({error:m},s,h);
const hex=(a:Uint8Array)=>[...a].map(b=>b.toString(16).padStart(2,"0")).join("");
async function sha256(v:string){return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v))))}
async function passwordHash(p:string,saltHex:string){const parts=saltHex.match(/../g)||[];const salt=new Uint8Array(parts.map(x=>parseInt(x,16)));const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(p),"PBKDF2",false,["deriveBits"]);return hex(new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations:210000},key,256)))}
async function body(req:Request){return await req.json<any>()}
async function session(env:Env,userId:number,schoolId:number){const token=hex(crypto.getRandomValues(new Uint8Array(32)));await env.DB.prepare("INSERT INTO sessions(user_id,school_id,token_hash,expires_at) VALUES(?,?,?,datetime('now','+30 days'))").bind(userId,schoolId,await sha256(token)).run();return token}
async function auth(req:Request,env:Env):Promise<Auth|null>{const h=req.headers.get("authorization");if(!h?.startsWith("Bearer "))return null;return await env.DB.prepare("SELECT u.id userId,u.school_id schoolId,u.role,u.full_name fullName,u.username FROM sessions s JOIN users u ON u.id=s.user_id JOIN schools sc ON sc.id=u.school_id WHERE s.token_hash=? AND s.expires_at>datetime('now') AND u.active=1 AND sc.active=1").bind(await sha256(h.slice(7))).first<Auth>()||null}
const admin=(a:Auth)=>["SUPER_ADMIN","SCHOOL_ADMIN","SECTION_HEAD"].includes(a.role);
async function classAllowed(env:Env,a:Auth,id:number){if(a.role!=="TEACHER")return !!await env.DB.prepare("SELECT id FROM classes WHERE id=? AND school_id=? AND active=1").bind(id,a.schoolId).first();return !!await env.DB.prepare("SELECT 1 FROM teacher_class_assignments t JOIN classes c ON c.id=t.class_id WHERE t.school_id=? AND t.teacher_id=? AND t.class_id=? AND c.active=1").bind(a.schoolId,a.userId,id).first()}
export default {async fetch(req:Request,env:Env):Promise<Response>{const u=new URL(req.url),p=u.pathname,h=cors(env);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:h});try{
if(p==="/api/public/status"&&req.method==="GET"){const r=await env.DB.prepare("SELECT COUNT(*) c FROM schools").first<{c:number}>();return json({initialized:(r?.c||0)>0},200,h)}
if(p==="/api/public/setup"&&req.method==="POST"){const n=await env.DB.prepare("SELECT COUNT(*) c FROM schools").first<{c:number}>();if((n?.c||0)>0)return fail("Platform has already been initialized.",409,h);const b=await body(req);if(!b.schoolName||!b.adminName||!b.username||!b.password)return fail("School and administrator details are required.",400,h);const sr=await env.DB.prepare("INSERT INTO schools(name,short_name,motto,app_name) VALUES(?,?,?,?)").bind(b.schoolName,b.shortName||null,b.motto||null,b.appName||"School Attendance App").run();const schoolId=Number(sr.meta.last_row_id),salt=hex(crypto.getRandomValues(new Uint8Array(16))),ph=await passwordHash(String(b.password),salt);const ur=await env.DB.prepare("INSERT INTO users(school_id,full_name,username,password_hash,password_salt,role) VALUES(?,?,?,?,?,'SCHOOL_ADMIN')").bind(schoolId,b.adminName,b.username,ph,salt).run();await env.DB.prepare("INSERT INTO school_settings(school_id) VALUES(?)").bind(schoolId).run();return json({token:await session(env,Number(ur.meta.last_row_id),schoolId)},201,h)}
if(p==="/api/login"&&req.method==="POST"){const b=await body(req),rows=await env.DB.prepare("SELECT u.*,s.active school_active FROM users u JOIN schools s ON s.id=u.school_id WHERE u.username=?").bind(String(b.username||"")).all<any>();let found:any=null;for(const r of rows.results){if(await passwordHash(String(b.password||""),r.password_salt)===r.password_hash){found=r;break}}if(!found||!found.active||!found.school_active)return fail("Invalid username or password.",401,h);return json({token:await session(env,found.id,found.school_id)},200,h)}
const a=await auth(req,env);if(!a)return fail("Please sign in to continue.",401,h);
if(p==="/api/logout"&&req.method==="POST"){const t=req.headers.get("authorization")!.slice(7);await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await sha256(t)).run();return json({ok:true},200,h)}
if(p==="/api/me"&&req.method==="GET"){const school=await env.DB.prepare("SELECT id,name,short_name,motto,logo_url,app_name,primary_color,secondary_color,accent_color,background_color FROM schools WHERE id=?").bind(a.schoolId).first();return json({user:{id:a.userId,full_name:a.fullName,username:a.username,role:a.role},school},200,h)}
if(p==="/api/dashboard"&&req.method==="GET"){const d=new Date().toISOString().slice(0,10),total=await env.DB.prepare("SELECT COUNT(*) c FROM students WHERE school_id=? AND status='ACTIVE'").bind(a.schoolId).first<{c:number}>(),present=await env.DB.prepare("SELECT COUNT(*) c FROM attendance_records r JOIN attendance_sessions s ON s.id=r.session_id WHERE r.school_id=? AND s.date=? AND r.status='PRESENT'").bind(a.schoolId,d).first<{c:number}>(),absent=await env.DB.prepare("SELECT COUNT(*) c FROM attendance_records r JOIN attendance_sessions s ON s.id=r.session_id WHERE r.school_id=? AND s.date=? AND r.status='ABSENT'").bind(a.schoolId,d).first<{c:number}>(),classes=await env.DB.prepare("SELECT c.id,c.display_name,CASE WHEN s.id IS NULL THEN 0 ELSE 1 END submitted FROM classes c LEFT JOIN attendance_sessions s ON s.class_id=c.id AND s.date=? AND s.school_id=c.school_id WHERE c.school_id=? AND c.active=1 ORDER BY c.display_name").bind(d,a.schoolId).all<any>();return json({totalStudents:total?.c||0,presentToday:present?.c||0,absentToday:absent?.c||0,submitted:classes.results.filter(x=>x.submitted).length,totalClasses:classes.results.length,pending:classes.results.filter(x=>!x.submitted)},200,h)}
if(p==="/api/grades"&&req.method==="GET")return json((await env.DB.prepare("SELECT id,name FROM grades WHERE school_id=? AND active=1 ORDER BY sort_order,name").bind(a.schoolId).all()).results,200,h);
if(p==="/api/grades"&&req.method==="POST"){if(!admin(a))return fail("You do not have permission to manage grades.",403,h);const b=await body(req),r=await env.DB.prepare("INSERT INTO grades(school_id,name) VALUES(?,?)").bind(a.schoolId,b.name).run();return json({id:r.meta.last_row_id},201,h)}
if(p==="/api/classes"&&req.method==="GET"){let q="SELECT id,grade_id,name,display_name,academic_year FROM classes WHERE school_id=? AND active=1",args:any[]=[a.schoolId];if(a.role==="TEACHER"){q+=" AND id IN (SELECT class_id FROM teacher_class_assignments WHERE school_id=? AND teacher_id=?)";args.push(a.schoolId,a.userId)}q+=" ORDER BY display_name";return json((await env.DB.prepare(q).bind(...args).all()).results,200,h)}
if(p==="/api/classes"&&req.method==="POST"){if(!admin(a))return fail("You do not have permission to manage classes.",403,h);const b=await body(req),g=await env.DB.prepare("SELECT id FROM grades WHERE id=? AND school_id=?").bind(b.grade_id,a.schoolId).first();if(!g)return fail("Invalid grade.",400,h);const r=await env.DB.prepare("INSERT INTO classes(school_id,grade_id,name,display_name,academic_year) VALUES(?,?,?,?,?)").bind(a.schoolId,b.grade_id,b.name,b.display_name,b.academic_year||null).run();return json({id:r.meta.last_row_id},201,h)}
if(p==="/api/students"&&req.method==="GET"){const classId=Number(u.searchParams.get("class_id")||0);if(classId&&!await classAllowed(env,a,classId))return fail("You do not have permission to view this class.",403,h);let q="SELECT s.id,s.admission_number,s.full_name,s.class_id,c.display_name class_name FROM students s JOIN classes c ON c.id=s.class_id WHERE s.school_id=? AND s.status='ACTIVE'",args:any[]=[a.schoolId];if(classId){q+=" AND s.class_id=?";args.push(classId)}else if(a.role==="TEACHER"){q+=" AND s.class_id IN (SELECT class_id FROM teacher_class_assignments WHERE school_id=? AND teacher_id=?)";args.push(a.schoolId,a.userId)}q+=" ORDER BY c.display_name,s.admission_number";return json((await env.DB.prepare(q).bind(...args).all()).results,200,h)}
if(p==="/api/students"&&req.method==="POST"){if(!admin(a))return fail("You do not have permission to add students.",403,h);const b=await body(req),c=await env.DB.prepare("SELECT grade_id FROM classes WHERE id=? AND school_id=?").bind(b.class_id,a.schoolId).first<{grade_id:number}>();if(!c)return fail("Invalid class.",400,h);try{const r=await env.DB.prepare("INSERT INTO students(school_id,admission_number,full_name,grade_id,class_id) VALUES(?,?,?,?,?)").bind(a.schoolId,b.admission_number,b.full_name,c.grade_id,b.class_id).run();return json({id:r.meta.last_row_id},201,h)}catch{return fail("This admission number already exists.",409,h)}}
if(p==="/api/teachers"&&req.method==="GET"){if(!admin(a))return fail("You do not have permission to view teachers.",403,h);return json((await env.DB.prepare("SELECT id,full_name,username,active FROM users WHERE school_id=? AND role='TEACHER' ORDER BY full_name").bind(a.schoolId).all()).results,200,h)}
if(p==="/api/teachers"&&req.method==="POST"){if(!admin(a))return fail("You do not have permission to create teachers.",403,h);const b=await body(req);if(String(b.password||"").length<4)return fail("Temporary password must be at least 4 characters.",400,h);const salt=hex(crypto.getRandomValues(new Uint8Array(16))),ph=await passwordHash(String(b.password),salt),r=await env.DB.prepare("INSERT INTO users(school_id,full_name,username,password_hash,password_salt,role,force_password_change) VALUES(?,?,?,?,?,'TEACHER',1)").bind(a.schoolId,b.full_name,b.username,ph,salt).run(),teacherId=Number(r.meta.last_row_id);for(const id of b.class_ids||[])await env.DB.prepare("INSERT OR IGNORE INTO teacher_class_assignments(school_id,teacher_id,class_id) SELECT ?,?,id FROM classes WHERE id=? AND school_id=?").bind(a.schoolId,teacherId,id,a.schoolId).run();return json({id:teacherId},201,h)}
if(p==="/api/attendance"&&req.method==="POST"){const b=await body(req);if(!await classAllowed(env,a,Number(b.class_id)))return fail("You do not have permission to submit attendance for this class.",403,h);const active=await env.DB.prepare("SELECT id FROM students WHERE school_id=? AND class_id=? AND status='ACTIVE'").bind(a.schoolId,b.class_id).all<any>(),ids=new Set(active.results.map(x=>x.id)),records=Array.isArray(b.records)?b.records:[];if(records.length!==ids.size||records.some((r:any)=>!ids.has(r.student_id)||!["PRESENT","ABSENT"].includes(r.status)))return fail("Attendance must be recorded for every active student.",400,h);await env.DB.prepare("INSERT INTO attendance_sessions(school_id,class_id,date,submitted_by) VALUES(?,?,?,?) ON CONFLICT(school_id,class_id,date) DO UPDATE SET submitted_by=excluded.submitted_by,updated_at=CURRENT_TIMESTAMP").bind(a.schoolId,b.class_id,b.date,a.userId).run();const s=await env.DB.prepare("SELECT id FROM attendance_sessions WHERE school_id=? AND class_id=? AND date=?").bind(a.schoolId,b.class_id,b.date).first<{id:number}>();for(const r of records)await env.DB.prepare("INSERT INTO attendance_records(school_id,session_id,student_id,status) VALUES(?,?,?,?) ON CONFLICT(session_id,student_id) DO UPDATE SET status=excluded.status,updated_at=CURRENT_TIMESTAMP").bind(a.schoolId,s!.id,r.student_id,r.status).run();return json({ok:true},200,h)}
if(p==="/api/attendance/history"&&req.method==="GET"){const rows=await env.DB.prepare("SELECT s.id,s.date,c.display_name class_name,u.full_name submitted_by,SUM(CASE WHEN r.status='PRESENT' THEN 1 ELSE 0 END) present_count,SUM(CASE WHEN r.status='ABSENT' THEN 1 ELSE 0 END) absent_count FROM attendance_sessions s JOIN classes c ON c.id=s.class_id JOIN users u ON u.id=s.submitted_by LEFT JOIN attendance_records r ON r.session_id=s.id WHERE s.school_id=? GROUP BY s.id ORDER BY s.date DESC LIMIT 200").bind(a.schoolId).all();return json(rows.results,200,h)}
if(p==="/api/teacher-period-attendance"&&req.method==="POST"){const b=await body(req);if(!await classAllowed(env,a,Number(b.class_id)))return fail("You do not have permission to submit this class.",403,h);for(const x of b.periods||[])await env.DB.prepare("INSERT INTO teacher_period_attendance(school_id,class_id,date,period,status,submitted_by) VALUES(?,?,?,?,?,?) ON CONFLICT(school_id,class_id,date,period) DO UPDATE SET status=excluded.status,submitted_by=excluded.submitted_by,updated_at=CURRENT_TIMESTAMP").bind(a.schoolId,b.class_id,b.date,x.period,x.status,a.userId).run();return json({ok:true},200,h)}
if(p==="/api/reports"&&req.method==="GET"){const start=u.searchParams.get("start")||"0000-00-00",end=u.searchParams.get("end")||"9999-12-31",rows=await env.DB.prepare("SELECT s.admission_number,s.full_name,c.display_name,COUNT(ar.id) total,SUM(CASE WHEN ar.status='PRESENT' THEN 1 ELSE 0 END) present,SUM(CASE WHEN ar.status='ABSENT' THEN 1 ELSE 0 END) absent FROM students s JOIN classes c ON c.id=s.class_id LEFT JOIN attendance_records ar ON ar.student_id=s.id LEFT JOIN attendance_sessions ss ON ss.id=ar.session_id WHERE s.school_id=? AND (ss.date BETWEEN ? AND ? OR ss.id IS NULL) GROUP BY s.id ORDER BY c.display_name,s.admission_number").bind(a.schoolId,start,end).all<any>();return json({headers:["Admission","Name","Class","Total Days","Present","Absent","Attendance %"],rows:rows.results.map(r=>[r.admission_number,r.full_name,r.display_name,r.total||0,r.present||0,r.absent||0,r.total?((r.present/r.total)*100).toFixed(1)+"%":"0.0%"])},200,h)}
return fail("Not found.",404,h)}catch(e){console.error(e);return fail("The request could not be completed.",500,h)}}};
