import {FormEvent,useEffect,useState} from "react";
const API=import.meta.env.VITE_API_BASE_URL||"http://localhost:8787";
async function api(path:string,options:RequestInit={}){const token=localStorage.getItem("sat_token"),headers=new Headers(options.headers||{});headers.set("Content-Type","application/json");if(token)headers.set("Authorization","Bearer "+token);const r=await fetch(API+path,{...options,headers}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request failed.");return d}
type C={id:number;display_name:string;grade_id:number};type S={id:number;admission_number:string;full_name:string;class_id:number};
export default function App(){const[ready,setReady]=useState<boolean|null>(null),[me,setMe]=useState<any>(null),[error,setError]=useState(""),[page,setPage]=useState("home"),[dash,setDash]=useState<any>(null),[classes,setClasses]=useState<C[]>([]),[students,setStudents]=useState<S[]>([]),[success,setSuccess]=useState("");
async function boot(){const s=await api("/api/public/status");setReady(s.initialized);if(localStorage.getItem("sat_token"))try{const m=await api("/api/me");setMe(m);document.documentElement.style.setProperty("--primary",m.school.primary_color||"#008759")}catch{localStorage.removeItem("sat_token")}}
useEffect(()=>{boot().catch(e=>setError(e.message))},[]);useEffect(()=>{if(me){api("/api/dashboard").then(setDash);api("/api/classes").then(setClasses)}},[me]);
async function setup(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const d=await api("/api/public/setup",{method:"POST",body:JSON.stringify({schoolName:f.get("schoolName"),shortName:f.get("shortName"),motto:f.get("motto"),appName:f.get("appName"),adminName:f.get("adminName"),username:f.get("username"),password:f.get("password")})});localStorage.setItem("sat_token",d.token);await boot()}catch(x:any){setError(x.message)}}
async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const d=await api("/api/login",{method:"POST",body:JSON.stringify({username:f.get("username"),password:f.get("password")})});localStorage.setItem("sat_token",d.token);await boot()}catch(x:any){setError(x.message)}}
async function logout(){try{await api("/api/logout",{method:"POST"})}catch{}localStorage.removeItem("sat_token");setMe(null)}
async function chooseClass(id:number){setStudents(id?await api("/api/students?class_id="+id):[])}
if(ready===null)return <div className="splash">Loading…</div>;
if(!ready)return <Auth title="First-time school setup" error={error}><form onSubmit={setup}><label>School Name<input name="schoolName" required/></label><label>Short Name<input name="shortName"/></label><label>Motto<input name="motto"/></label><label>App Name<input name="appName" defaultValue="School Attendance App"/></label><label>Administrator Name<input name="adminName" required/></label><label>Username<input name="username" required/></label><label>Password<input name="password" type="password" minLength={6} required/></label><button>Create School</button></form></Auth>;
if(!me)return <Auth title="Sign in" error={error}><form onSubmit={login}><label>Username<input name="username" required/></label><label>Password<input name="password" type="password" required/></label><button>Login</button></form></Auth>;
const isAdmin=["SUPER_ADMIN","SCHOOL_ADMIN","SECTION_HEAD"].includes(me.user.role);const nav=[["home","Home"],["attendance","Attendance"],["history","History"],...(isAdmin?[["manage","Manage"]]:[]),["profile","Profile"]];
return <div className="shell"><aside><div className="school"><b>{me.school.name}</b><small>{me.school.app_name}</small></div>{nav.map(n=><button className={page===n[0]?"active":""} onClick={()=>setPage(n[0])} key={n[0]}>{n[1]}</button>)}<button onClick={logout}>Logout</button></aside><main><header><h1>{page[0].toUpperCase()+page.slice(1)}</h1><p>{me.user.full_name} · {me.user.role.replaceAll("_"," ")}</p></header>{error&&<div className="error">{error}</div>}
{page==="home"&&<><div className="brandline"><div className="logo">{(me.school.short_name||me.school.name).slice(0,2).toUpperCase()}</div><div><h2>{me.school.app_name}</h2><p>{me.school.motto||me.school.name}</p></div></div><div className="stats"><Card t="Total Students" v={dash?.totalStudents||0}/><Card t="Present Today" v={dash?.presentToday||0}/><Card t="Absent Today" v={dash?.absentToday||0}/><Card t="Submitted" v={dash?(dash.submitted+"/"+dash.totalClasses):"0/0"}/></div><div className="card"><h3>Class Status</h3>{classes.map(c=><div className="row" key={c.id}><span>{c.display_name}</span><b>{dash?.pending?.some((x:any)=>x.id===c.id)?"Not Submitted":"Submitted"}</b></div>)}</div></>}
{page==="attendance"&&<div className="card"><h2>Student Attendance</h2><label>Class<select onChange={e=>chooseClass(Number(e.target.value))}><option value="">Select</option>{classes.map(c=><option value={c.id} key={c.id}>{c.display_name}</option>)}</select></label><Attendance students={students} classes={classes} done={()=>{setSuccess("Attendance has been saved.");api("/api/dashboard").then(setDash)}}/></div>}
{page==="history"&&<History/>}{page==="manage"&&isAdmin&&<Manage classes={classes} refresh={()=>api("/api/classes").then(setClasses)}/>}
{page==="profile"&&<div className="card"><h2>{me.user.full_name}</h2><p>@{me.user.username}</p><p>{me.user.role.replaceAll("_"," ")}</p><button onClick={logout}>Logout</button></div>}</main><div className="bottom">{nav.map(n=><button className={page===n[0]?"active":""} onClick={()=>setPage(n[0])} key={n[0]}>{n[1]}</button>)}</div>{success&&<div className="modalbg"><div className="modal"><b>✓</b><h2>Submitted Successfully</h2><p>{success}</p><button onClick={()=>setSuccess("")}>OK</button></div></div>}</div>}
function Auth(p:any){return <div className="auth"><div className="brand"><h1>School Attendance</h1><p>Simple · Smart · Reliable</p></div><div className="card authcard"><h2>{p.title}</h2>{p.error&&<div className="error">{p.error}</div>}{p.children}</div></div>}
function Card({t,v}:{t:string,v:any}){return <div className="card stat"><span>{t}</span><strong>{v}</strong></div>}
function Attendance({students,classes,done}:{students:S[];classes:C[];done:()=>void}){const[classId,setClassId]=useState(0);useEffect(()=>{if(students[0])setClassId(students[0].class_id)},[students]);async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!classId)return;const f=e.currentTarget,records=students.map(s=>({student_id:s.id,status:String((f.elements.namedItem("s"+s.id) as RadioNodeList).value||"PRESENT")}));await api("/api/attendance",{method:"POST",body:JSON.stringify({class_id:classId,date:new FormData(f).get("date"),records})});done()}return students.length?<form onSubmit={send}><input type="hidden" value={classId} readOnly/><label>Date<input type="date" name="date" defaultValue={new Date().toISOString().slice(0,10)}/></label>{students.map(s=><div className="student" key={s.id}><div><b>{s.full_name}</b><small>{s.admission_number}</small></div><div><label><input type="radio" name={"s"+s.id} value="PRESENT" defaultChecked/> Present</label><label><input type="radio" name={"s"+s.id} value="ABSENT"/> Absent</label></div></div>)}<button>Submit Attendance</button></form>:<p>Select a class to load students.</p>}
function History(){const[rows,setRows]=useState<any[]>([]);useEffect(()=>{api("/api/attendance/history").then(setRows)},[]);return <div className="card"><h2>Attendance History</h2>{rows.length?rows.map(r=><div className="row" key={r.id}><span>{r.date} · {r.class_name}</span><span>{r.present_count||0} present · {r.absent_count||0} absent</span></div>):<p>No attendance submitted yet.</p>}</div>}
function Manage({classes,refresh}:{classes:C[];refresh:()=>void}){const[grades,setGrades]=useState<any[]>([]);useEffect(()=>{api("/api/grades").then(setGrades)},[]);async function grade(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/api/grades",{method:"POST",body:JSON.stringify({name:f.get("name")})});setGrades(await api("/api/grades"));e.currentTarget.reset()}async function cls(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/api/classes",{method:"POST",body:JSON.stringify({grade_id:Number(f.get("grade_id")),name:f.get("name"),display_name:f.get("display_name"),academic_year:f.get("academic_year")})});refresh();e.currentTarget.reset()}async function student(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/api/students",{method:"POST",body:JSON.stringify({admission_number:f.get("admission"),full_name:f.get("full_name"),class_id:Number(f.get("class_id"))})});e.currentTarget.reset()}async function teacher(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/api/teachers",{method:"POST",body:JSON.stringify({full_name:f.get("full_name"),username:f.get("username"),password:f.get("password"),class_ids:[Number(f.get("class_id"))]})});e.currentTarget.reset()}return <div className="manage"><form className="card" onSubmit={grade}><h3>Add Grade</h3><input name="name" placeholder="Grade 10" required/><button>Add</button></form><form className="card" onSubmit={cls}><h3>Add Class</h3><select name="grade_id" required><option value="">Grade</option>{grades.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select><input name="name" placeholder="A" required/><input name="display_name" placeholder="10-A" required/><input name="academic_year" placeholder="2026"/><button>Add</button></form><form className="card" onSubmit={student}><h3>Add Student</h3><input name="admission" placeholder="Admission number" required/><input name="full_name" placeholder="Full name" required/><select name="class_id" required><option value="">Class</option>{classes.map(c=><option value={c.id} key={c.id}>{c.display_name}</option>)}</select><button>Add</button></form><form className="card" onSubmit={teacher}><h3>Add Teacher</h3><input name="full_name" placeholder="Full name" required/><input name="username" placeholder="Username" required/><input name="password" placeholder="Temporary password" required/><select name="class_id" required><option value="">Assigned class</option>{classes.map(c=><option value={c.id} key={c.id}>{c.display_name}</option>)}</select><button>Add</button></form></div>}
