import { Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } from "docx";
import { jsPDF } from "jspdf";

export type AttendanceReportRow = {
  date: string;
  class_name: string;
  present_count: number;
  absent_count: number;
  submitted_by: string;
};

type Format = "pdf" | "docx";
const MIMES: Record<Format,string> = {
  pdf: "application/pdf",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
};

function text(value:unknown):string {return String(value??"").replace(/[\r\n\t]+/g," ").trim()}
const rowValues=(r:AttendanceReportRow)=>[text(r.date),text(r.class_name),String(Number(r.present_count)||0),String(Number(r.absent_count)||0),text(r.submitted_by)];

async function saveReport(blob:Blob, filename:string, format:Format):Promise<void>{
  const native=window.MaestroAndroid?.saveReportFile;
  if(typeof native==="function"){
    // Android WebView's DownloadManager cannot consume blob: URLs and may terminate the app.
    const base64=await new Promise<string>((resolve,reject)=>{
      const reader=new FileReader();
      reader.onerror=()=>reject(new Error("Could not prepare report for saving."));
      reader.onload=()=>resolve(String(reader.result).split(",")[1]||"");
      reader.readAsDataURL(blob);
    });
    if(!base64)throw new Error("Generated report is empty.");
    if(base64.length>16*1024*1024)throw new Error("Report is too large for mobile export.");
    native(filename,MIMES[format],base64);
    return;
  }
  const url=URL.createObjectURL(blob);
  const link=document.createElement("a");
  link.href=url;link.download=filename;
  document.body.appendChild(link);link.click();link.remove();
  window.setTimeout(()=>URL.revokeObjectURL(url),30000);
}

export async function exportAttendanceReport(format:Format, month:string, rows:AttendanceReportRow[]):Promise<void>{
  if(!rows.length)throw new Error("No attendance submissions to export for this month.");
  const fileName="maestro-attendance-"+month+"."+format;
  const count=rows.reduce((n,r)=>n+Number(r.present_count||0)+Number(r.absent_count||0),0);
  const present=rows.reduce((n,r)=>n+Number(r.present_count||0),0);
  const absent=count-present;
  const rate=count?((present/count)*100).toFixed(1):"0.0";
  const header=["Date","Class","Present","Absent","Submitted by"];
  const data=rows.map(rowValues);
  if(format==="docx"){
    const cell=(value:string,headerCell=false)=>new TableCell({children:[new Paragraph({children:[new TextRun({text:value,bold:headerCell})]})]});
    const report=new Document({sections:[{
      properties:{},
      children:[
        new Paragraph({text:"MAESTRO | ATTENDANCE REPORT",heading:HeadingLevel.HEADING_1}),
        new Paragraph({text:"Reporting month: "+month}),
        new Paragraph({text:"Submissions: "+rows.length+"    Present: "+present+"    Absent: "+absent+"    Attendance rate: "+rate+"%"}),
        new Paragraph({text:"Submitted attendance records",heading:HeadingLevel.HEADING_2}),
        new Table({
          width:{size:100,type:WidthType.PERCENTAGE},
          rows:[
            new TableRow({children:header.map(h=>cell(h,true))}),
            ...data.map(values=>new TableRow({children:values.map(v=>cell(v))}))
          ]
        }),
        new Paragraph({text:"Generated by Maestro School Attendance."})
      ]
    }]});
    await saveReport(await Packer.toBlob(report),fileName,format);
  }else{
    const pdf=new jsPDF({orientation:"landscape",unit:"mm",format:"a4"});
    const margin=12,pageHeight=210,lineHeight=8;
    let y=18;
    const line=(values:string[],widths:number[],bold=false)=>{
      if(y+lineHeight>pageHeight-margin){pdf.addPage();y=18;drawHeader()}
      pdf.setFont("helvetica",bold?"bold":"normal");pdf.setFontSize(9);
      let x=margin;
      values.forEach((value,i)=>{
        const printable=value.replace(/[^\x20-\x7e]/g,"?");
        const lines=pdf.splitTextToSize(printable,Math.max(10,widths[i]-3));
        pdf.text(lines[0]||"",x,y);
        x+=widths[i];
      });
      y+=lineHeight;
    };
    const widths=[34,77,32,32,88];
    const drawHeader=()=>line(header,widths,true);
    pdf.setFontSize(17);pdf.setFont("helvetica","bold");
    pdf.text("MAESTRO | ATTENDANCE REPORT",margin,y);y+=10;
    pdf.setFontSize(11);pdf.setFont("helvetica","normal");
    pdf.text("Month: "+month+"  |  Submissions: "+rows.length+"  |  Present: "+present+"  |  Absent: "+absent+"  |  Attendance: "+rate+"%",margin,y);y+=12;
    drawHeader();
    for(const values of data)line(values,widths);
    pdf.setProperties({title:"Maestro attendance report "+month,subject:"Monthly submitted attendance"});
    await saveReport(pdf.output("blob"),fileName,format);
  }
}
